version: '3'

volumes:
  database_data:
    driver: local
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - database_data:/var/lib/mysql
      - ./data/sql/shorty.sql:/docker-entrypoint-initdb.d/shorty.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shorty
      MYSQL_USER: username
      MYSQL_PASSWORD: password
